CREATE DATABASE IF NOT EXISTS Ejercicio1;
USE Ejercicio1;

CREATE TABLE LOCALIDAD (
    Cod_Localidad INT PRIMARY KEY NOT NULL,
    Nombre VARCHAR(40) NOT NULL
);

CREATE TABLE PUB (
    Cod_Pub VARCHAR(40) PRIMARY KEY,
    nombre VARCHAR(40) NOT NULL,
    Licencia_Fiscal VARCHAR(20) UNIQUE NOT NULL,
    Domicilio VARCHAR(100),
    Fecha_Apertura DATE NOT NULL,
    Horario VARCHAR (70) NOT NULL,
    Cod_Localidad INT NOT NULL,
    FOREIGN KEY (Cod_Localidad) REFERENCES  (Cod_Localidad)

    ALTER TABLE PUB ADD CONSTRAINT ck_horario
    CHECK (Horario IN ('HOR1', 'HOR2', 'HOR3'));
);

CREATE TABLE EMPLEADO (
    Dni_Empleado VARCHAR(10) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(40) NOT NULL,
    Domicilio VARCHAR(100)
);

CREATE TABLE TITULAR (
    Dni_Titular VARCHAR(10) PRIMARY KEY,
    Nombre VARCHAR(40) NOT NULL,
    Domicilio VARCHAR(100),
    Cod_Pub VARCHAR(40) NOT NULL,
    FOREIGN KEY (Cod_Pub) REFERENCES PUB(Cod_Pub)
);

CREATE TABLE EXISTENCIAS (
    Cod_Articulo VARCHAR(20) PRIMARY KEY NOT NULL,
    Nombre VARCHAR(40) NOT NULL,
    Cantidad INT NOT NULL,
    Precio DECIMAL(6,2) NOT NULL,
    Cod_Pub VARCHAR(40) NOT NULL,
    FOREIGN KEY (Cod_Pub) REFERENCES PUB(Cod_Pub)
);

CREATE TABLE PUB_EMPLEADO (
    Cod_Pub VARCHAR(40) NOT NULL,
    Dni_Empleado VARCHAR(10) NOT NULL,
    Funcion ENUM('CAMARERO', 'SEGURIDAD', 'LIMPIEZA') NOT NULL,
    PRIMARY KEY (Cod_Pub, Dni_Empleado, Funcion),
    FOREIGN KEY (Cod_Pub) REFERENCES PUB(Cod_Pub),
    FOREIGN KEY (Dni_Empleado) REFERENCES EMPLEADO(Dni_Empleado)

    ALTER TABLE PUB_EMPLEADO ADD CONSTRAINT ck_funcion
    CHECK (Funcion IN ('CAMARERO', 'SEGURIDAD', 'LIMPIEZA'));

    
);

