CREATE DATABASE IF NOT EXISTS Ejercicio3;
USE Ejercicio3;

-- 1. DEPARTAMENTOS (Independiente)
CREATE TABLE DEPARTAMENTOS (
    DPTO_COD INT PRIMARY KEY,
    NOMBRE_DPTO VARCHAR(30) NOT NULL UNIQUE, 
    DPTO_PADRE INT,
    PRESUPUESTO INT NOT NULL, 
    PRES_ACTUAL INT,
    CONSTRAINT fk_depto_padre FOREIGN KEY (DPTO_PADRE) REFERENCES DEPARTAMENTOS(DPTO_COD)
);

-- 2. UNIVERSIDADES (Independiente)
CREATE TABLE UNIVERSIDADES (
    UNIV_COD INT PRIMARY KEY,
    NOMBRE_UNIV VARCHAR(25) NOT NULL,
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    COD_POSTAL VARCHAR(5)
);

-- 3. TRABAJOS (Independiente)
CREATE TABLE TRABAJOS (
    TRABAJO_COD INT PRIMARY KEY,
    NOMBRE_TRAB VARCHAR(20) NOT NULL UNIQUE, 
    SALARIO_MIN INT NOT NULL, 
    SALARIO_MAX INT NOT NULL  
);

-- 4. EMPLEADOS (Dependediente de Departamentos)
CREATE TABLE EMPLEADOS (
    DNI NUMBER (8) PRIMARY KEY,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    DIRECC1 VARCHAR(25),
    DIRECC2 VARCHAR(20),
    CIUDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    COD_POSTAL VARCHAR(5),
    SEXO VARCHAR(1),
    FECHA_NAC DATE,
    CONSTRAINT chk_sexo CHECK (SEXO IN ('H', 'M')) -
);

-- 5. ESTUDIOS (Tabla intermedia: Empleado - Universidad)
CREATE TABLE ESTUDIOS (
    EMPLEADO_DNI INT,
    UNIVERSIDAD_COD INT,
    AÑO INT,
    GRADO VARCHAR(3),
    ESPECIALIDAD VARCHAR(20),
    PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD_COD, GRADO), 
    CONSTRAINT fk_estudios_emp FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    CONSTRAINT fk_estudios_univ FOREIGN KEY (UNIVERSIDAD_COD) REFERENCES UNIVERSIDADES(UNIV_COD)
);

-- 6. HISTORIAL_LABORAL
CREATE TABLE HISTORIAL_LABORAL (
    EMPLEADO_DNI INT,
    TRABAJO_COD INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD INT,
    SUPERVISOR_DNI NUMBER (8) NOT NULL,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_INICIO), 
    CONSTRAINT fk_hist_lab_emp FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    CONSTRAINT fk_hist_lab_trab FOREIGN KEY (TRABAJO_COD) REFERENCES TRABAJOS(TRABAJO_COD),
    CONSTRAINT fk_hist_lab_dpto FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS(DPTO_COD),
    CONSTRAINT fk_hist_lab_superv FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS(DNI)
);

-- 7. HISTORIAL_SALARIAL
CREATE TABLE HISTORIAL_SALARIAL (
    EMPLEADO_DNI INT,
    SALARIO INT NOT NULL, 
    FECHA_COMIENZO DATE,
    FECHA_FIN DATE,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO), 
    CONSTRAINT fk_hist_sal_emp FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI)
);