[8-Enero]
css pseudo-clases
:NOT()
:IS()
:HAS()

Jerarquia

#ID
·Clases
:Pseudo-clases
::Pseudo-elementos


[9-Enero]

Fase de pruebas:
(DESARROLLO DE UNA APP)
-Pruebas de caja blanca
-Pruebas de caja negra

[14-Enero]
-Casos de pruebas

				¿Qué se prueba?
OBJETIVOS -->	¿Cómo se prueba?
				Resultados esperados
				
				
